- become: yes
  hosts: all
  name: configuration
  tasks:
    - name: Install git package
      apt:
        name: git
        update_cache: yes
        state: latest

    - name: Install bash package
      apt:
        name: bash
        update_cache: yes
        state: latest
      
    - name: Creates directory
      file:
        path: /home/chaosmonkey/download/
        state: directory
        owner: chaosmonkey
        group: chaosmonkey
        mode: '0755'

    - name: Creates chaos-monkey log directory
      file:
        path: /data/chaos-monkey/
        state: directory
        owner: chaosmonkey
        group: chaosmonkey
        mode: '0755'

    - name: Creates chaos-monkey backup log directory
      file:
        path: /data/chaos-monkey/backup/
        state: directory
        owner: root
        group: root
        mode: '0744'

######
###### ssh configuration for backup
######
    - name: Copy private ssh-key to remote host
      ansible.builtin.copy:
        src: /Users/pbu/id_rsa
        dest: /home/chaosmonkey/.ssh/id_rsa
        owner: chaosmonkey
        group: chaosmonkey
        mode: '0600'

######
###### Clone Chaos-Monkey Git-Repository
######
    - name: Git checkout
      ansible.builtin.git:
        repo: https://github.com/buehlmannpa/application-digitalocean-chaosmonkey.git
        dest: /home/chaosmonkey/chaosmonkey-app
        version: main

######
###### DigitalOcean 'doctl'
######
    - name: Download DigitalOcean 'doctl'
      get_url:
        url: https://github.com/digitalocean/doctl/releases/download/v1.72.0/doctl-1.72.0-linux-amd64.tar.gz
        dest: /home/chaosmonkey/download
        mode: '0755'

    - name: Extract doctl.tar.gz into /home/chaosmonkey/download
      ansible.builtin.unarchive:
        copy: remote_src=True
        src: /home/chaosmonkey/download/doctl-1.72.0-linux-amd64.tar.gz
        dest: /home/chaosmonkey/download

    - name: Create a symbolic link for 'doctl'
      ansible.builtin.file:
        src: /home/chaosmonkey/download/doctl
        dest: /usr/local/bin/doctl
        owner: root
        group: root
        state: link

    - name: Copy DigitalOcean API Token
      ansible.builtin.copy:
        src: /Users/pbu/do_token
        dest: /home/chaosmonkey/chaosmonkey-app
        owner: root
        group: root
        mode: '0644'


######
###### Install kubectl
######
    - name: add kubectl apt repository key
      become: true
      apt_key:
        url: https://packages.cloud.google.com/apt/doc/apt-key.gpg

    - name: add kubectl apt repository
      become: true
      apt_repository:
        repo: 'deb https://apt.kubernetes.io/ kubernetes-xenial main'
        filename: kubectl

    - name: install kubectl
      become: true
      apt:
        name: kubectl


######
###### Start Chaos-Monkey
######
    - name: Execute chaos-monkey
      command: /home/chaosmonkey/chaosmonkey-app/chaosmonkey.sh

#    - name: log in as ubuntu and do something as scrapy
#      remote_user: chaosmonkey
#      sudo: true
#      sudo_user: scrapy
#      shell: /home/chaosmonkey/chaosmonkey-app/chaosmonkey.sh


######
###### GitHub Repo
######
#    - name: Clone a github repository
#      git:
#        repo: https://github.com/buehlmannpa/terraform-digitalocean-chaosmonkey.git
#        dest: /home/chaosmonkey/test
#        clone: yes
#        update: yes
##
#
##https://gist.github.com/devynspencer/effa29af449c46477ac71213210e7043
#    - name: add github ssh key
#      copy: >
#        src=/Users/pbu/.ssh/id_rsa
#        dest=/root/.ssh/id_rsa.github
#        owner=root
#        group=root
#        mode=0600
#    
#    - name: configure ssh to use ansible key for github.com
#      template: >
#        src=ssh_config.j2
#        dest=/root/.ssh/config
#        owner=root
#        group=root
#        mode=0644
#        
#    - name: clone a private repository
#      git: >
#        repo=ssh://git@github.com:buehlmannpa/terraform-digitalocean-chaosmonkey.git
#        key_file=/root/.ssh/id_rsa.github
#        dest=/opt/example